### ISSUE TITLE
大佬，带图评价晒单好像挂了

### ISSUE THREAD

**Issue by toobye** [shufflewzc/faker3#108]
♻️当前使用内置sign(推荐)，自定义变量SIGN_URL

当前版本：20240623 差评内容关键词
每次运行最多20个账号，每个账号最多评价10个商品
问题反馈：https://t.me/dylan_jdpro
屏蔽差评内容关键词：["垃圾","质量差","差评","好差","欺骗"]

******开始【京东账号1】jd_753d2921683q7*********

TypeError: bdy_0x59e2f9[bdy_0x3fd237] is not a function
    at bdy_0x6f02ce (/ql/data/scripts/shufflewzc_faker3_main/jd_AutoEval.js:6:109343)
    at bdy_0x2359c2 (/ql/data/scripts/shufflewzc_faker3_main/jd_AutoEval.js:6:105625)
    at bdy_0x4c24ba (/ql/data/scripts/shufflewzc_faker3_main/jd_AutoEval.js:6:70335)
    at /ql/data/scripts/shufflewzc_faker3_main/jd_AutoEval.js:6:56133
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
出错了，反馈作者修！！！

**Comment by star2005** [comment]
带图评价刚运行了，没问题。qinglong 2.15.15 + Node依赖库  sharp@0.31.0
