### ISSUE TITLE
互助报错

### ISSUE THREAD

**Issue by gclm** [shufflewzc/faker3#15]
```
❗️京喜工厂互助版, 错误!
TypeError: Cannot read properties of undefined (reading 'assistListToday')
    at /ql/data/scripts/shufflewzc_faker3_main/jd_dreamFactory_Mod.js:551:23
    at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/ql/data/scripts/shufflewzc_faker3_main/jd_dreamFactory_Mod.js:1683:5721)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by shufflewzc** [comment]
已修复
