### ISSUE TITLE
获取互助码 task shufflewzc_faker3_jd_get_share_code.js 执行还是会报错，并没有修复

### ISSUE THREAD

**Issue by jkingben** [shufflewzc/faker3#19]
#11 

青龙脚本编辑里，我用github上的整个替换了一遍，再次运行任务，还是这个错

**Comment by shufflewzc** [comment]
具体报的是什么错？

**Comment by DaPoHou** [comment]
是的 ，同样报错。
报错内容是
`❗️获取互助码, 错误!
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at /ql/scripts/shufflewzc_faker3/jd_get_share_code.js:599:18
    at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/ql/scripts/shufflewzc_faker3/jd_get_share_code.js:756:4869)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)`
使用https://github.com/zero205/JD_tencent_scf/blob/main/jd_get_share_code.js
是正常的。
