### ISSUE TITLE
京喜特价赚金币提示api错误

### ISSUE THREAD

**Issue by jim4ever** [shufflewzc/faker3#39]
京喜特价赚金币
shufflewzc_faker3_main/jd_speed_sign.js
运行时提示错误：
"Response code 403 (Forbidden)"
京喜特价赚金币 API请求失败，请检查网路重试
"Response code 403 (Forbidden)"
京喜特价赚金币 API请求失败，请检查网路重试

**Comment by Drz-Drz** [comment]
一样  前几天开始这样子了

**Comment by caiop11** [comment]
一样，更新了脚本也是不行

**Comment by caiop11** [comment]
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at safeGet (/scripts/jd_speed_sign.js:724:21)
    at /scripts/jd_speed_sign.js:611:15
    at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/scripts/jd_speed_sign.js:755:4869)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
京东服务器访问数据为空，请检查自身设备网络情况
"Response code 403 (Forbidden)"
京东极速版 API请求失败，请检查网路重试
"Response code 403 (Forbidden)"
京东极速版 API请求失败，请检查网路重试
签到失败，活动下柜
"Response code 403 (Forbidden)"
京东极速版 API请求失败，请检查网路重试
"Response code 403 (Forbidden)"
京东极速版 API请求失败，请检查网路重试
"Response code 403 (Forbidden)"
京东极速版 API请求失败，请检查网路重试

**Comment by caiop11** [comment]
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at safeGet (/scripts/jd_speed_sign.js:724:21)
    at /scripts/jd_speed_sign.js:611:15
    at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/scripts/jd_speed_sign.js:755:4869)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
京东服务器访问数据为空，请检查自身设备网络情况
"Response code 403 (Forbidden)"
京东极速版 API请求失败，请检查网路重试
"Response code 403 (Forbidden)"
京东极速版 API请求失败，请检查网路重试
签到失败，活动下柜
"Response code 403 (Forbidden)"
京东极速版 API请求失败，请检查网路重试
"Response code 403 (Forbidden)"
京东极速版 API请求失败，请检查网路重试
"Response code 403 (Forbidden)"
京东极速版 API请求失败，请检查网路重试

**Comment by ns5394** [comment]
我的一样情况，不过自己手动运行正常，可能是脚本都是定时运行，并发量太大。
