### ISSUE TITLE
炸年兽出错

### ISSUE THREAD

**Issue by Raytow** [shufflewzc/faker3#43]
==================脚本执行- 北京时间(UTC+8)：2022/1/12 20:35:57=====================

Faker 友情提示：您的脚本正常运行中

【温馨提示】
默认膨胀时间：22时， 默认开启膨胀红包时间：23时
如不需要自动膨胀请设置环境变量 JD_TRAVEL_EXPAND=-1
如需自动膨胀请注意设置好corn时间差，如22:00，23:00运行则刚好错过膨胀红包，22:30,23:00运行则助力基本可以成功
******开始【京东账号1】*********

{
  functionId: 'tigernian_collectAutoScore',
  errMsg: '啊哦，活动太火爆了，请稍后再试~（-1002）',
  curlCmd: `curl -H 'Cookie: __jd_ref_cls=Babel_dev_adv_selfReproduction; mba_muid=16419909873669719390391.20.1641990987425; mba_sid=20.132; shshshfpb=sO6YC24MKuJcYWg3Rpi76uO%3D%3D; __jda=122270672.16419909873669719390391.1641990987.1641996672.1641992818.4; __jdb=122270672.8.16419909873669719390391%7C4.1641990987; __jdc=122270672; pre_seq=93; pre_session=0d70900856a5ddbcb9a60a5ee37efa7750822cae%7C78; pt_key=AAJh3oO6ADCy2E2DkdqBB2JPPq17ZbTbwmAasCSmf86PLjrgYSV1lsVXjmiv8rR-rBgPP89gbB0; pt_pin=jd_IEHfkoaIEDdT; joyytoken=50089MDJtdUx5UjA0MQ==.XEN4SGtURXVBZVhEfQcFBjo0LxdfHxs1LFxZelVlQUcySyxcCzI=.88fa2c78; pwdt_id=jd_IEHfkoaIEDdT; shshshfp=82a2ca09f2749d6672eeca2dd1fee734; shshshfpa=89c4a9ff-f0fe-8e55-7273-29f3440921db-1641990987; shshshsID=43365fce18310cc6275c608f3cc1a1f4_4_1641990987425; sid=6a19c45e46fb42d63c525361659c3047; wxa_level=1; cid=8; __jdv=122270672%7Cdirect%7C-%7Cnone%7C-%7C1641990987366;' -H 'Host: api.m.jd.com' -H 'Origin: https://wbbny.m.jd.com' -H 'Referer: https://wbbny.m.jd.com/babelDiy/Zeus/2vVU4E7JLH9gKYfLQ5EVW6eN2P7B/index.html' -H 'Connection: keep-alive' -H 'Content-Type: application/x-www-form-urlencoded' -H 'User-Agent: jdapp;iPhone;10.1.4;14.3.1;0d70900856a5ddbcb9a60a5ee37efa7750822cae;M/5.0;network/5g;ADID/;model/iPhone13,1;addressid/;appBuild/167814;jdSupportDarkMode/0;Mozilla/5.0 (iPhone; CPU iPhone OS 14_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148;supportJDSHWK/1;' -H 'Accept: application/json, text/plain, */*' -H 'Accept-Language: zh-cn' -H 'Accept-Encoding: gzip, deflate, br' --data-raw 'functionId=tigernian_collectAutoScore&body=%7B%22ss%22%3A%22%7B%5C%22extraData%5C%22%3A%7B%5C%22log%5C%22%3A%5C%221641990987864~1e8nCvAGhWTMDJtdUx5UjA0MQ%3D%3D.XEN4SGtURXVBZVhEfQcFBjo0LxdfHxs1LFxZelVlQUcySyxcCzI%3D.88fa2c78~7%2C2~8035401EE3F0B347FAE1833A8C7CD583712ECB6FF660B5AD7BAEC5A6E58B9A51~09pwu8t~C~ShJFWxAKahNXBh0CeR9odhkAAwIcUhhFEh0UVgYcZgscZQsUY2weVB9EEW0fFkVeXBQIaxNVBh0HChR%2BAB5nYBxGHEcWHRJVAR9nCR1mCRx2fR9ZHkERHBFUBhlkCR1hcBwFYx9FHEYabhQQUkFeEQoBGBNDQhQIEgAHBwEJCwgKAAUNBQQLBwQNExwTQVdUEwsRRERGTEdeR1MRHBFHVlUTChNQVERFRUdFURAUEUhWWxEKaAEDGAMHCBoGHAAAHwEcBGUfGlhfEQoCHBFXQhILFFAHAFMKVFRTXlYNAgYBBwVSAFBXBFQABAgCBgoEVgpaERQQW0MSCRJaZFlfX1MQHBNFEQoBBAwCAQsFCggECAUAHRJbXRAKEwFXBwALCAMABwNSBVdUUVdTCVAAAlEEVFYDB1deUg8FAAMIAQJQVVQSHRRUQFMTCRJDfQ5qewABfntGelBtZlcCZEJZBgdGfw0PGh8aXEMRChFxQ0RdVRF1XV1BREdVQh4YelZRGxEcEV5SQhMKEwcEBwkABxIcEEtQShAPaAgGBB8ACQBsGhBCXhMJaxJbaFtXXFACAx8BERgTWX5lEBwTAAceAxwJERQQBAMeAh4HFh0SAAAFCAAFERwSAlwECAsFAwgGBlIBVVRTVVAJUAcDUQVXXQAPV1NSBwQFAwwDAlJXVxIdE1ISbR4aWldTFwkSVVZVUldWRUIQHBNQWRIKEE0RFBBWWhIJEkQHHwIfAhAcE1JVb0YQAhEIAxcfElFUEQ4TQlBYVl9cDAQEBQoIBgwLFx8SXloRDmoCHQYeAGwdEVJcXV8RAhAEBQQCCQoECAgGAgAFTwBlA0B0e3dSd2BCfXd2YGNnZnJkdnFJf3INDRxhAQFaVgABQVFkTAdTA2RCUmVJSmpifxN4VkVNY3dQAnxdYwF9BAdFV1xUQlR2SFlyS0YOHgoFUQcCUwBXTEkdAE1OTnBGYFB4ZGRIdnt2WHh0eXd7ZHljeWF1RUtkb1p0VXVfSHJxYFdjc1pHZWNxcXt3T2p9c2RiZHRydWZnZwh%2Bd1daYHJHdWFwYXJzcFRDZ3VbDGVndG9gc3N0cnhhc3xyX39me3J9YnZ1XmR0BgINTwBcAUdACQIaHhdeQ1QSCRYTTQ%3D%3D~0jh6pg7%5C%22%2C%5C%22sceneid%5C%22%3A%5C%22ZNShPageh5%5C%22%7D%2C%5C%22secretp%5C%22%3A%5C%22m2BosTtWVUwevCCAVOq3FCk6hQ%5C%22%2C%5C%22random%5C%22%3A%5C%2274580549%5C%22%7D%22%7D&client=wh5&clientVersion=1.0.0' --compressed "https://api.m.jd.com/client.action?functionId=tigernian_collectAutoScore"`
}
TypeError: Cannot read properties of null (reading 'produceScore')
    at travel (/ql/scripts/shufflewzc_faker3/jd_travel.js:189:30)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /ql/scripts/shufflewzc_faker3/jd_travel.js:87:13

**Comment by JAXHA** [comment]
换IP 也解决不了

**Comment by verages** [comment]
> ==================脚本执行- 北京时间(UTC+8)：2022/1/12 20:35:57=====================
> 
> Faker 友情提示：您的脚本正常运行中
> 
> 【温馨提示】 默认膨胀时间：22时， 默认开启膨胀红包时间：23时 如不需要自动膨胀请设置环境变量 JD_TRAVEL_EXPAND=-1 如需自动膨胀请注意设置好corn时间差，如22:00，23:00运行则刚好错过膨胀红包，22:30,23:00运行则助力基本可以成功 ******开始【京东账号1】*********
> 
> { functionId: 'tigernian_collectAutoScore', errMsg: '啊哦，活动太火爆了，请稍后再试~（-1002）', curlCmd: `curl -H 'Cookie: __jd_ref_cls=Babel_dev_adv_selfReproduction; mba_muid=16419909873669719390391.20.1641990987425; mba_sid=20.132; shshshfpb=sO6YC24MKuJcYWg3Rpi76uO%3D%3D; __jda=122270672.16419909873669719390391.1641990987.1641996672.1641992818.4; __jdb=122270672.8.16419909873669719390391%7C4.1641990987; __jdc=122270672; pre_seq=93; pre_session=0d70900856a5ddbcb9a60a5ee37efa7750822cae%7C78; pt_key=AAJh3oO6ADCy2E2DkdqBB2JPPq17ZbTbwmAasCSmf86PLjrgYSV1lsVXjmiv8rR-rBgPP89gbB0; pt_pin=jd_IEHfkoaIEDdT; joyytoken=50089MDJtdUx5UjA0MQ==.XEN4SGtURXVBZVhEfQcFBjo0LxdfHxs1LFxZelVlQUcySyxcCzI=.88fa2c78; pwdt_id=jd_IEHfkoaIEDdT; shshshfp=82a2ca09f2749d6672eeca2dd1fee734; shshshfpa=89c4a9ff-f0fe-8e55-7273-29f3440921db-1641990987; shshshsID=43365fce18310cc6275c608f3cc1a1f4_4_1641990987425; sid=6a19c45e46fb42d63c525361659c3047; wxa_level=1; cid=8; __jdv=122270672%7Cdirect%7C-%7Cnone%7C-%7C1641990987366;' -H 'Host: api.m.jd.com' -H 'Origin: https://wbbny.m.jd.com' -H 'Referer: https://wbbny.m.jd.com/babelDiy/Zeus/2vVU4E7JLH9gKYfLQ5EVW6eN2P7B/index.html' -H 'Connection: keep-alive' -H 'Content-Type: application/x-www-form-urlencoded' -H 'User-Agent: jdapp;iPhone;10.1.4;14.3.1;0d70900856a5ddbcb9a60a5ee37efa7750822cae;M/5.0;network/5g;ADID/;model/iPhone13,1;addressid/;appBuild/167814;jdSupportDarkMode/0;Mozilla/5.0 (iPhone; CPU iPhone OS 14_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148;supportJDSHWK/1;' -H 'Accept: application/json, text/plain, */*' -H 'Accept-Language: zh-cn' -H 'Accept-Encoding: gzip, deflate, br' --data-raw 'functionId=tigernian_collectAutoScore&body=%7B%22ss%22%3A%22%7B%5C%22extraData%5C%22%3A%7B%5C%22log%5C%22%3A%5C%221641990987864~1e8nCvAGhWTMDJtdUx5UjA0MQ%3D%3D.XEN4SGtURXVBZVhEfQcFBjo0LxdfHxs1LFxZelVlQUcySyxcCzI%3D.88fa2c78~7%2C2~8035401EE3F0B347FAE1833A8C7CD583712ECB6FF660B5AD7BAEC5A6E58B9A51~09pwu8t~C~ShJFWxAKahNXBh0CeR9odhkAAwIcUhhFEh0UVgYcZgscZQsUY2weVB9EEW0fFkVeXBQIaxNVBh0HChR%2BAB5nYBxGHEcWHRJVAR9nCR1mCRx2fR9ZHkERHBFUBhlkCR1hcBwFYx9FHEYabhQQUkFeEQoBGBNDQhQIEgAHBwEJCwgKAAUNBQQLBwQNExwTQVdUEwsRRERGTEdeR1MRHBFHVlUTChNQVERFRUdFURAUEUhWWxEKaAEDGAMHCBoGHAAAHwEcBGUfGlhfEQoCHBFXQhILFFAHAFMKVFRTXlYNAgYBBwVSAFBXBFQABAgCBgoEVgpaERQQW0MSCRJaZFlfX1MQHBNFEQoBBAwCAQsFCggECAUAHRJbXRAKEwFXBwALCAMABwNSBVdUUVdTCVAAAlEEVFYDB1deUg8FAAMIAQJQVVQSHRRUQFMTCRJDfQ5qewABfntGelBtZlcCZEJZBgdGfw0PGh8aXEMRChFxQ0RdVRF1XV1BREdVQh4YelZRGxEcEV5SQhMKEwcEBwkABxIcEEtQShAPaAgGBB8ACQBsGhBCXhMJaxJbaFtXXFACAx8BERgTWX5lEBwTAAceAxwJERQQBAMeAh4HFh0SAAAFCAAFERwSAlwECAsFAwgGBlIBVVRTVVAJUAcDUQVXXQAPV1NSBwQFAwwDAlJXVxIdE1ISbR4aWldTFwkSVVZVUldWRUIQHBNQWRIKEE0RFBBWWhIJEkQHHwIfAhAcE1JVb0YQAhEIAxcfElFUEQ4TQlBYVl9cDAQEBQoIBgwLFx8SXloRDmoCHQYeAGwdEVJcXV8RAhAEBQQCCQoECAgGAgAFTwBlA0B0e3dSd2BCfXd2YGNnZnJkdnFJf3INDRxhAQFaVgABQVFkTAdTA2RCUmVJSmpifxN4VkVNY3dQAnxdYwF9BAdFV1xUQlR2SFlyS0YOHgoFUQcCUwBXTEkdAE1OTnBGYFB4ZGRIdnt2WHh0eXd7ZHljeWF1RUtkb1p0VXVfSHJxYFdjc1pHZWNxcXt3T2p9c2RiZHRydWZnZwh%2Bd1daYHJHdWFwYXJzcFRDZ3VbDGVndG9gc3N0cnhhc3xyX39me3J9YnZ1XmR0BgINTwBcAUdACQIaHhdeQ1QSCRYTTQ%3D%3D~0jh6pg7%5C%22%2C%5C%22sceneid%5C%22%3A%5C%22ZNShPageh5%5C%22%7D%2C%5C%22secretp%5C%22%3A%5C%22m2BosTtWVUwevCCAVOq3FCk6hQ%5C%22%2C%5C%22random%5C%22%3A%5C%2274580549%5C%22%7D%22%7D&client=wh5&clientVersion=1.0.0' --compressed "https://api.m.jd.com/client.action?functionId=tigernian_collectAutoScore"` } TypeError: Cannot read properties of null (reading 'produceScore') at travel (/ql/scripts/shufflewzc_faker3/jd_travel.js:189:30) at processTicksAndRejections (node:internal/process/task_queues:96:5) at async /ql/scripts/shufflewzc_faker3/jd_travel.js:87:13

已经火爆了，禁用掉，手动刷，或者等等看有没有更新
