### ISSUE TITLE
农场执行报错

### ISSUE THREAD

**Issue by clhlc** [shufflewzc/faker3#55]
## 开始执行... 2023-08-29 10:21:17

🔔东东农场日常任务, 开始!
node:internal/modules/cjs/loader:1080
  throw err;
  ^

Error: Cannot find module './function/krgetToken'
Require stack:
- /ql/data/scripts/shufflewzc_faker3/jd_fruit_task.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/ql/data/scripts/shufflewzc_faker3/jd_fruit_task.js:42:1812)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/ql/data/scripts/shufflewzc_faker3/jd_fruit_task.js' ]
}

Node.js v18.17.0

## 执行结束... 2023-08-29 10:21:18  耗时 1 秒

**Comment by bcoderi** [comment]
报错+1

**Comment by Z2112** [comment]
报错+1

**Comment by Marblog** [comment]
## 开始执行... 2023-08-30 12:05:00

/ql/shell/otask.sh: line 5: [[: "": syntax error: operand expected (error token is """")

🔔东东农场日常任务, 开始!
/usr/local/bin/ds:2
# -*- coding: utf-8 -*-
^

SyntaxError: Invalid or unexpected token
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1178:20)
    at Module._compile (node:internal/modules/cjs/loader:1220:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/ql/data/scripts/shufflewzc_faker3_main/function/cache/index.js:1:9455)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)

Node.js v18.17.0


## 执行结束... 2023-08-30 12:05:00  耗时 1 秒

**Comment by clhlc** [comment]
需要copy function 目录到/ql/data/scripts 下

**Comment by SnailInLeaves** [comment]
> ## 开始执行... 2023-08-30 12:05:00
> /ql/shell/otask.sh: line 5: [[: "": syntax error: operand expected (error token is """")
> 
> 🔔东东农场日常任务, 开始! /usr/local/bin/ds:2
> 
> # -_- coding: utf-8 -_-
> ^
> 
> SyntaxError: Invalid or unexpected token at internalCompileFunction (node:internal/vm:73:18) at wrapSafe (node:internal/modules/cjs/loader:1178:20) at Module._compile (node:internal/modules/cjs/loader:1220:27) at Module._extensions..js (node:internal/modules/cjs/loader:1310:10) at Module.load (node:internal/modules/cjs/loader:1119:32) at Module._load (node:internal/modules/cjs/loader:960:12) at Module.require (node:internal/modules/cjs/loader:1143:19) at require (node:internal/modules/cjs/helpers:110:18) at Object. (/ql/data/scripts/shufflewzc_faker3_main/function/cache/index.js:1:9455) at Module._compile (node:internal/modules/cjs/loader:1256:14)
> 
> Node.js v18.17.0
> 
> ## 执行结束... 2023-08-30 12:05:00 耗时 1 秒

+1
