### ISSUE TITLE
同步代码后 jd_fruit_task.js 执行出错了

### ISSUE THREAD

**Issue by lxmicode** [shufflewzc/faker3#70]
TypeError: DS is not a constructor
    at new Cache (/root/faker3/function/cache/index.js:1:11084)
    at Object.<anonymous> (/root/faker3/function/krgetToken.js:15:1776)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/root/faker3/fruit_task.js:40:1794)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)

Node.js v18.17.0

**Comment by shufflewzc** [comment]
已修复，拉库即可
