### ISSUE TITLE
京东资产变动报错

### ISSUE THREAD

**Issue by gm-fire** [shufflewzc/faker3#88]
检测到资产变动缓存文件2024-01-27.json，载入...
检测到未配置Wxpusher的Token，禁用一对一推送...
******开始查询【京东账号1】g*********
TypeError: Cannot read properties of undefined (reading 'length')
    at CheckEcard (/ql/data/scripts/shufflewzc_faker3_main/jd_bean_change.js:1124:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 3)
    at async /ql/data/scripts/shufflewzc_faker3_main/jd_bean_change.js:410:4

**Comment by shufflewzc** [comment]
@gm-fire 待修复
