### ISSUE TITLE
种豆得豆内部互助

### ISSUE THREAD

**Issue by y525455383** [shufflewzc/faker3#92]
遇到这个错误了，请问怎么解决呢？
<img width="365" alt="Snipaste_2024-02-12_19-59-54" src="https://github.com/shufflewzc/faker3/assets/95900668/d684139d-d2dc-4aeb-9a1e-921f47a9fc10">

**Comment by y525455383** [comment]
获取任务及基本信息
"getaddrinfo ENOTFOUND kr.kingran.cf"
种豆得豆内部互助 getH5st API请求失败，请检查网路重试
undefined

❗️种豆得豆内部互助, 错误!
TypeError: Cannot read properties of undefined (reading 'roundList')
    at jdPlantBean (/ql/data/scripts/shufflewzc_faker3_main/jd_plantBean_help.js:27:6201)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /ql/data/scripts/shufflewzc_faker3_main/jd_plantBean_help.js:27:4140
